package com.example.logistics.myBatis.model;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.COUNTRY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.NAME
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPANY.ID
     *
     * @return the value of PUBLIC.COMPANY.ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPANY.ID
     *
     * @param id the value for PUBLIC.COMPANY.ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPANY.COUNTRY
     *
     * @return the value of PUBLIC.COMPANY.COUNTRY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPANY.COUNTRY
     *
     * @param country the value for PUBLIC.COMPANY.COUNTRY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPANY.NAME
     *
     * @return the value of PUBLIC.COMPANY.NAME
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPANY.NAME
     *
     * @param name the value for PUBLIC.COMPANY.NAME
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}