package com.example.logistics.myBatis.model;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.ID
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.FIRST_NAME
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.IDENTIFICATION_NUMBER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    private String identificationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.LAST_NAME
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.COMPANY_ID
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.ID
     *
     * @return the value of PUBLIC.DRIVER.ID
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.ID
     *
     * @param id the value for PUBLIC.DRIVER.ID
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.FIRST_NAME
     *
     * @return the value of PUBLIC.DRIVER.FIRST_NAME
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.DRIVER.FIRST_NAME
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.IDENTIFICATION_NUMBER
     *
     * @return the value of PUBLIC.DRIVER.IDENTIFICATION_NUMBER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public String getIdentificationNumber() {
        return identificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.IDENTIFICATION_NUMBER
     *
     * @param identificationNumber the value for PUBLIC.DRIVER.IDENTIFICATION_NUMBER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.LAST_NAME
     *
     * @return the value of PUBLIC.DRIVER.LAST_NAME
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.DRIVER.LAST_NAME
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.COMPANY_ID
     *
     * @return the value of PUBLIC.DRIVER.COMPANY_ID
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.COMPANY_ID
     *
     * @param companyId the value for PUBLIC.DRIVER.COMPANY_ID
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}