package com.example.logistics.myBatis.model;

public class Truck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRUCK.ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRUCK.CAPACITY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private Integer capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRUCK.MODEL
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRUCK.COMPANY_ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRUCK.ID
     *
     * @return the value of PUBLIC.TRUCK.ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRUCK.ID
     *
     * @param id the value for PUBLIC.TRUCK.ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRUCK.CAPACITY
     *
     * @return the value of PUBLIC.TRUCK.CAPACITY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRUCK.CAPACITY
     *
     * @param capacity the value for PUBLIC.TRUCK.CAPACITY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRUCK.MODEL
     *
     * @return the value of PUBLIC.TRUCK.MODEL
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRUCK.MODEL
     *
     * @param model the value for PUBLIC.TRUCK.MODEL
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRUCK.COMPANY_ID
     *
     * @return the value of PUBLIC.TRUCK.COMPANY_ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRUCK.COMPANY_ID
     *
     * @param companyId the value for PUBLIC.TRUCK.COMPANY_ID
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}