package com.example.logistics.myBatis.dao;

import com.example.logistics.myBatis.model.Company;
//import org.apache.ibatis.annotations.Mapper;

import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    Company selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int updateByPrimaryKey(Company record);
}