package com.example.logistics.myBatis.dao;

import com.example.logistics.myBatis.model.Company;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    Company selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    int updateByPrimaryKey(Company record);
}