package com.example.logistics.myBatis.dao;

import com.example.logistics.myBatis.model.Driver;
import com.example.logistics.myBatis.model.Truck;
//import org.apache.ibatis.annotations.Mapper;

import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    Driver selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int updateByPrimaryKey(Driver record);

    List<Driver> findByCompany(Long companyId);
}