package com.example.logistics.myBatis.dao;

import com.example.logistics.myBatis.model.Driver;
import com.example.logistics.myBatis.model.Truck;

import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    Driver selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Sat Apr 12 03:06:25 EEST 2025
     */
    int updateByPrimaryKey(Driver record);
    List<Driver> findByCompany(Long companyId);
}