package com.example.logistics.myBatis.dao;

import com.example.logistics.myBatis.model.Truck;
//import org.apache.ibatis.annotations.Mapper;

import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface TruckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRUCK
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRUCK
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int insert(Truck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRUCK
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    Truck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRUCK
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    List<Truck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRUCK
     *
     * @mbg.generated Wed Apr 17 15:12:15 EEST 2024
     */
    int updateByPrimaryKey(Truck record);

    List<Truck> findByCompany(Long companyId);
}